import Head from 'next/head';

import Header from '@/components/Header';
import HomeArticles from '@/components/HomeArticles';
import Subscribe from '@/components/Subscribe';
import CategoriesHome from '@/components/CategoriesHome';

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <CategoriesHome />
        <Subscribe />
        <HomeArticles data={props.data} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(`${process.env.API_HOST}articles-home?page=1`);
  const data = await response.json();

  return { props: { data } };
}

// masalah image sizes
// buat meta head
// favicon dan judul tiap halaman

// IDEA LISTS

// di halaman article, di tengah konten dibuat box rekomendasi artikle yang berhubungan dengan artikle tsb berdasarkan label, di backend data nya dikirim bareng dengan artikel tsb

// di halaman article bagian bawah buat related article
